apiVersion: v1
kind: Namespace
metadata:
  name: wedding-prod
  labels:
    kubernetes.io/metadata.name: wedding-prod
---
apiVersion: v1
kind: Namespace
metadata:
  name: wedding-staging
  labels:
    kubernetes.io/metadata.name: wedding-staging