apiVersion: v1
kind: Secret
metadata:
  name: wedding-secret
  namespace: wedding-prod
type: Opaque
data:
  DB_PASSWORD: cm9vdA==
  JWT_SECRET: MDc2SmFuaXRoQA==
  DATABASE_URL: bXlzcWw6Ly9yb290OjA3Nkphbml0aEBAcGxhY2Vob2xkZXI6MzMwNi9pbnZpdGVhcHA=