apiVersion: v1
kind: ServiceAccount
metadata:
  name: wedding-sa
  namespace: wedding-prod
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::140023361098:oidc-provider/oidc.eks.us-east-1.amazonaws.com/id/C68D674DB3DCB07CEEAE5BC81E56F1D6