import type { Metadata } from "next";
import "../globals.css";
import { Ruda, Indie_Flower, Satisfy, Poppins } from 'next/font/google';
import Sidebar from "../components/sidebar";
import Navbar from "../components/navbar";
import PageFooter from "../components/pagefooter";

const indie = Indie_Flower({
  subsets: ["latin"],
  variable: "--font-indie",
  weight: "400",
});

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: "400",
});

const ruda = Ruda({
  subsets: ["latin"],
  variable: "--font-ruda",
  weight: "400", // Choose the appropriate weight as per the Google Fonts page
});

const satisfy = Satisfy({
  subsets: ["latin"],
  variable: "--font-satisfy",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${indie.variable} ${ruda.variable} ${satisfy.variable} ${poppins.variable}`}>
        <div className="drawer lg:drawer-open min-h-screen">
          <input id="my-drawer-2" type="checkbox" className="drawer-toggle" />
          <div className="drawer-content flex flex-col">
            {/* Navbar and Page content */}
            <Navbar/>
            {children}
          </div>
          <div className="drawer-side">
            <label htmlFor="my-drawer-2" className="drawer-overlay"></label>
            <Sidebar />
          </div>
        </div>
      </body>
    </html>
  );
}
